### ISSUE TITLE
"default" to be typed to Default<string> for InputQuestion

### ISSUE THREAD

**Issue by matiboy** [TylorS/typed-prompts#1]
**Code to reproduce the issue:**
```
    prompt([input('age', 'Age'),
    input('participant_age', 'Participant age (minimum 18)', {
      default: answers => {
        let age = parseInt(answers.age);
        if(age >= 18) {
          return age.toString();
        }
        return '';
      })])
```

**Expected behavior:**
`default` can be a string or a function that returns a string. Typing to Default<string> would allow correct behavior.

**Actual behavior:**
Currently this is rejected by the definition which is only <string>

**Versions of packages used:**
"typed-prompts": "^1.0.0"

Thank you for coming up with the definitions for `inquirer`! Really useful

**Comment by TylorS** [comment]
Should be fixed in v1.1.0. Thanks for the issue :D
